# Generated by Django 5.2.11 on 2026-02-25 03:00

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', validators=[posts.models.validar_arquivo]),
        ),
    ]
